# .streamlit/secrets.toml

gemini_api_key = "AIzaSyDZlcscHMoil1Kr5MfyBfJOsZeTWJyor5A"
testrail_url = "https://bscqa.testrail.io"
testrail_email = "radames@bsc.com.do"
testrail_api_key = "sVqkc.oPRtlnDQraSqfK-0ULMdhAbfyiBzqEqPCSB"