# .streamlit/secrets.toml

gemini_api_key = "AIzaSyDulxWh82qNRHZMN_HJ6qKRg0MJ4IokJCY"
testrail_url = "https://bscqa.testrail.io"
testrail_email = "radames@bsc.com.do"
testrail_api_key = "sVqkc.oPRtlnDQraSqfK-0ULMdhAbfyiBzqEqPCSB"
